language: node_js
node_js: 
 - "13"
services:
 - docker 
before script:
   - npm install

scripts:
 - docker build -t udagram-api-feed ./udagram-api-feed
 - docker build -t udagram-api-user ./udagram-api-user
 - docker build -t udagram-reverseproxy ./udagram-reverseproxy
 - docker build -t udagram-frontend ./udagram-frontend

 # Tagging
 - docker tag udagram-api-feed mackray94/udagram-api-feed:v1
 - docker tag udagram-api-user mackray94/udagram-api-user:v1
 - docker tag udagram-reverseproxy mackray94/udagram-reverseproxy:v1
 - docker tag udagram-frontend mackray94/udagram-frontend:local
 
after_script:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push mackray94/udagram-api-feed:v1
 - docker push mackray94/udagram-api-user:v1
 - docker push mackray94/udagram-reverseproxy:v1
 - docker push mackray94/udagram-frontend:local
