apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app.kubernetes.io/name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: reverseproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverseproxy
    spec:
     containers:
      - image: docker.io/mackray94/reverseproxy:v1   
        name: reverseproxy
        ports:  
        - containerPort: 8080
          protocol: TCP
        resources: 
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
          
   







  
