version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build docker container
          command: |
             echo "-----------installing dependecies--------"
             node --version => v18.0.0
             sudo apt install nodejs 

             echo "-----------building image---------"
             docker build -t udagram-api-feed ./udagram-api-feed
             docker tag udagram-api-feed mackray94/udagram-api-feed:v3

             docker build -t udagram-api-user ./udagram-api-user
             docker tag udagram-api-user mackray94/udagram-api-user:v3

             docker build -t udagram-reverseproxy ./udagram-reverseproxy
             docker tag udagram-reverseproxy mackray94/reverseproxy:v3

             docker build -t udagram-frontend ./udagram-frontend
             docker tag udagram-frontend mackray94/udagram-frontend:local

             echo "-----------All image successfully built-------"
             
             docker login -u mackray94

             echo "-----------pushing images to docker--------" 
             docker push mackray94/udagram-api-feed:v3
             docker push mackray94/udagram-api-user:v3
             docker push mackray94/reverseproxy:v3
             docker push mackray94/udagram-frontend:local
workflows:
  default:
    jobs:
      - lint-app:
           context: lint-app
      - build-docker:
           requires: [lint-app]
