apiVersion: apps/v1

kind: Deployment

metadata:

  name: backend-feed-deployment

  labels:

    app: backend-feed

spec:

  replicas: 2

  selector:

    matchLabels:

      app: backend-feed

  template:

    metadata:

      labels:

        app: backend-feed

    spec:

      containers:

      - name: backend-feed

        image: mackray94/udagram-api-feed:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 8080

        resources:

          limits:

            memory: 512Mi

            cpu: 500m

          requests:

            memory: 256Mi

            cpu: 200m
      
   







  
