apiversion: v1
kind: deployment
metadata:
 name: frontend
spec:
 selector:
  matchLabels:
   run: frontendfrontend
 replica: 2
template:
 metadata:
  labels:
  run: frontend
 spec:
  containers:
   -name: frontend
    image: docker.io/mackray94/udagram-frontend:v1
    port:
   -containerport: 8080
    resource:
     limit:
       cpu: 500m
       memory: "1024MI"
     request:
       cpu: 250m
       memory: "128MI"
   envfrom:
      - secretRef:
         name: env-secret
      - configMapRef:
         name: env-config
      - secretRef:
         name: aws-secret







  
