apiversion: v1
kind: deployment
metadata:
 name: reverseproxy
spec:
 selector:
  matchLabels:
   run: reverseproxy
 replica: 2
template:
 metadata:
  labels:
  run: reverseproxy
 spec:
  containers:
   -name: reverseproxy
    image: docker.io/mackray94/udagram-reverseproxy:v1
    port:
    -containerport: 8080
    resource:
     limit:
       cpu: 500m
       memory: "1024MI"
     request:
       cpu: 250m
       memory: "128MI"
   envfrom:
      - secretRef:
         name: env-secret
      - configMapRef:
         name: env-config
      - secretRef:
         name: aws-secret







  
