apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
  - name: 8080
    protocol: TCP
    port: 8080
    targetPort: 8080